### ISSUE TITLE
Hi, is the sdram module works ?sdram模块能正常工作吗？

### ISSUE THREAD

**Issue by tscmga** [wuhanstudio/picorv32_tang#1]
您好。我跑起来了。
就是串口通信 进了shell。。。
问题就是我不知道sdram模块是不是正常工作。。。rtthreader里面好像也没有检测sdram的函数
还有就是我的时钟是24m。我改了pll。运行在72m没有问题。
现在就是我想用里面的sdram模块。。。代码比较晦涩。。。所以我问一下

**Comment by wuhanstudio** [comment]
你好，sdram 模块是正常工作的，这里可以看到 SoC 加载了 sdram：

https://github.com/wuhanstudio/picorv32_EG4S20/blob/6479c943d7b327c410df3e84eb900568293239a3/hx8kdemo.v#L181-L204

rt-thread 里没有检测 sdram 的函数是因为，这里的 sdram 模块是作为 CPU 内部 SRAM 使用的，所以不需要操作系统初始化。

**Comment by tscmga** [comment]
您好。因为您的sdram模块的代码是机器生成的。。我又着急。我联系了安陆的技术。加了微型。说了10多条。人家一句都没有回我。所以我找了一个人写的在学习。。。以后我再也不用安陆的fpga了

**Comment by tscmga** [comment]
就是icesugar pro我也有。也是您搞的。

**Comment by tscmga** [comment]
我改了时钟的频率。144m。因为机器生成的代码不好修改。所以我放弃了

**Comment by tscmga** [comment]
我还想说的就是sdram模块并不是接上就好了的。。。因为不能工作他也不会报错。。。
